### ISSUE TITLE
wrong formula in fragment spectrum and rare NaNs

### ISSUE THREAD

**Issue by rickhelmus** [boecker-lab/sirius#10]
Hello,

Using the CLI, I found some inconsistencies when specifying another adduct than `[M+H]+`. I am trying to figure out what's going here and I could use some help :-)

A minimal example:

input spectrum:
```>compound unknownCompound
>parentmass 100.024448818631
>ionization [M+NH3+H]+
>ms1peaks
100.024448818631 92749.5607638889

>ms2peaks
100.075553894043 2571.09342447917
```

The command is run without any specials, other than setting ionization to `[M+NH3+H]+` with the `-i` option.

Then looking at `formula_candidates.tsv`:
```
rank	molecularFormula	adduct	precursorFormula	TreeIsotope_Score	Tree_Score	Isotope_Score	explainedPeaks	explainedIntensity	medianMassError(ppm)	massError(ppm)
1	H2O5	[M + H3N + H]+	H5NO5	0.0	0.0	0.0	1	0.0	NaN	4.000087430558615
```

and the resulting fragment spectrum file, `H5NO5_[M+H3N+H]+.tsv`:
```
mz	intensity	rel.intensity	exactmass	formula	ionization
100.024449	0.00	0.00	82.997500	H2O5	[M + H]+
```

Questions/Remarks:
1. What is the `precursorFormula` column supposed to be in the `formula_candidates.tsv file`? From the past I know that this column is always equal to molecularFormula when having `[M+H]+` adducts. Is it simply always the deprotonated form?
2. Bug: the `medianMassError` from `formula_candidates.tsv` gives a `NaN` here :(
3. The file name of the spectrum file seems to match that of `precursorFormula` from the candidates file, is that always the case? Again, when using `[M+H]+` this equals that of the `molecularFormula`.
4. The ionization column in the spectrum file suddenly says `[M + H]+`. 

Thanks,
Rick

**Comment by marcus-ludwig** [comment]
> 1. What is the `precursorFormula` column supposed to be in the `formula_candidates.tsv file`? From the past I know that this column is always equal to molecularFormula when having `[M+H]+` adducts. Is it simply always the deprotonated form?

The precursor is the adduct that is selected for MS/MS. Hence, `molecularFormula` is the neutral molecular formula of the compound and `percursorFormula` the neutral formula of the measured adduct (in your case the [M+NH4]+).

> 2. Bug: the `medianMassError` from `formula_candidates.tsv` gives a `NaN` here :(

The `medianMassError` is a measure of the fragments in MS/MS. In your minimal example the MS/MS only contains one peak with m/z greater than the precursor mass. Therefore, the calculated fragmentation tree contains no fragments that can be used to calculate a median mass error. We might adjust the naming of this column to make this more intuitive.  

> 3. The file name of the spectrum file seems to match that of `precursorFormula` from the candidates file, is that always the case? Again, when using `[M+H]+` this equals that of the `molecularFormula`.

Yes, we name the spectrum and fragmentation tree files based on the `precursorFormula` and adduct to indicate the adduct that was measured by MS/MS.

> 4. The ionization column in the spectrum file suddenly says `[M + H]+`.

We differentiate "ionization" and "adduct". Ionizations are simple ion modes such as [M+H]+, [M+K]+ or [M+Na]+. And adduct might include another adduct fragment or in-source fragment ([M+NH3+H]+ or [M-H2O+H]+). Simply looking at the MS/MS, it is not obvious to differentiate if an MS/MS spectrum was produced by [H5NO5+H]+ or [H2O5+NH3+H]+. Because of that, we only considered the simple ion modes in the past. And currently, we still annotate the peaks in the spectrum file in this way. But since we now include feature detection in our workflow, we can estimate adducts of the precursor based on the MS1 more frequently. And based on the precursor adduct we can also make suggestions of the fragment adducts.
We had a discussion on that yesterday and decided that we will also annotate peaks in the spectrum file with a possible adduct type in cases where we estimate one based on the fragmentation trees. However, these adducts will always be suggestions since e.g. fragments [C6H15NO6+H]+ and [C6H12O6+NH3+H]+ produce the exact same m/z. 

I hope this clarification helps.

Best,
Marcus

**Comment by marcus-ludwig** [comment]
I hope the answers helped to resolve your questions. I will close this issue for now.

**Comment by rickhelmus** [comment]
Hi Marcus,

Many thanks for all the explanations, that clarifies it well :-)
