### ISSUE TITLE
Email and password printed out in terminal

### ISSUE THREAD

**Issue by eeko-kon** [boecker-lab/sirius#110]
Hi!

Is there a way to avoid/suppress printing out both the email and password arguments in the terminal using the CLI?

command:

`sirius login --email=**@**.dtu.dk --password=****`

output on terminal: 

`INFO    22:26:38 - Running with following arguments: [login, --email=***@**.dtu.dk, --password=****]`

Thank you:)

**Comment by mfleisch** [comment]
Hey Efi,
thanks for reporting.  I agree we should not print the commands for the `login` subtool and we will change this in the next release. 

You can get around this problem as follows:

The password parameter is should to be used als interactive parameter in the terminal:
`sirius login --user=user@email.com --password` 
Otherwise the password may be added to the terminal history.

For use in automated workflows username and password can be loaded from environment variables.
`sirius login --user-env=USER_ENV --password=PW_ENV`
In that case you can simply use the environment variable name and must not expand it.
The output would then look like this `[login, --user-env=USER_ENV, --password-env=PW_ENV]`.
