### ISSUE TITLE
Unexpected molecular formulas in fragment annotations by Sirius 

### ISSUE THREAD

**Issue by AharoniLab** [boecker-lab/sirius#117]
Hi,

Is Sirius possibly explaining fragments with non-canonical molecular formulas ?

I came across several spectra, where the parent ion is the Sodium adduct ([M+Na]+) and in all of these cases, the molecular formulas explaining the MS2 fragments were all also corresponding with the Sodium ion, instead of the formula corresponding with the expected [M+H]+ ion, so e.g.:  fragment of m/z 91.05182 was explained by the formula C5H8, corresponding with 91.05182 - 22.98922 (mass of the Sodium ion) = 68.06260 Da.

I could not find a similar issue with any of the other adducts observed in our systems, i.e.: in all cases where the precursor ion was annotated as  [M-H]-, [M+COOH]-, [M+H]+,[M+NH4]+,[M-H2O+H]+, etc. the corresponding fragments were explained by either the de-protonated or protonated ions. Is this a bug, an intended property or some wrong parameter setting on my part?

**Comment by kaibioinfo** [comment]
Hi, SIRIUS distinguishes between  "ionization modes" and "adducts/in-source fragments". This distinction has mostly a historical reason, but to be honest, I still don't know how to solve that better.

Ionization modes are [M+H], [M+Na]+, [M+K]+ in positive mode and [M-H]-, [M+Cl]-, [M+Br]- in negative mode. The basic idea of an ionization mode is that it cannot change during fragmenation. Once protonated, always protonated (within the same MSMS!).

Adducts/In source fragments however are just "modifications of the molecular formula". The idea is, that we cannot distinguish if a molecule is an in-source fragment or not without looking into the MS1. If we just have the MSMS given, it could be [M+H]+, [M-H2O+H]+, [M-H4O2+H]+ and so on and there is no way to find out given the spectrum. Because all these variants have basically the same MSMS interpretation (just with tiny modifications of the precursor formula) we do not compute an individual fragmentation tree for each of them, but instead, compute one for the [M+H]+ variant and then just modify the tree by removing the H2O or H4O2 to obtain the tree for [M-H2O+H]+ and [M-H4O2+H]+, respectively.

This also comes from a time where SIRIUS was not able to process complete LC-MS/MS runs and, thus, we couldn't find out adduct information by looking for correlated ions in the LC-MS.

Later we find out that ion modes can indeed change. The most common example is [M+Na]+ which sometimes switch to [M+H]+ during fragmentation. Thus, we changed the rules and allowed for these cases. But, still, a MS/MS with [M+H]+ and with [M+Na]+ would have completely different interpretations, so it still makes sense to distinguish between precursor ion modifications (like water loss or NH3 adduct) and ionization modes (like Na+, H+ and so on).

TLTR: It's the intended behaviour.

**Comment by AharoniLab** [comment]
Hi Kai,

Thanks. It seems to me an over-complication of the reality. In our "book" there are only two ionization modes and then precursor modifications are many, and often vary between systems. Fragmentation in our systems typically do not display any adduct modifications due to to the dissociation forces in the collision cell - but I cannot completely exclude this possibility. Have you any literature references for all the fragment modification variants which are embedded into Sirius? I saw in a recent publication that fragment bindings to ambient water or nitrogen ions are considered: https://doi.org/10.48550/arXiv.2301.11419 
...however I find it hard to accept losses of water or waters dimers - it would then be a different fragment structure, wouldn't it?

Anyway, my motivation was to use the Sirius explanations to calibrate mass fragments measured on an older QTOF HRMS which we found can deviate by as large as 50ppm for the lower abundance ions - but with all this going on in the background I am wondering if it's not too risky.

Bests/
