### ISSUE TITLE
The differences between table formula_identifications_adducts and formula_identifications

### ISSUE THREAD

**Issue by peijiying** [boecker-lab/sirius#120]
Upon comparing the tables of formula_identifications_Addicts and formulas_identifications, it was observed that the only disparity between the two tables lies in the rank column. Is this divergence attributed to the variation in the top ion types taken into account during the calculation of rankings? which table is more reliable in identify the molecular formula? Thank you for the reply.

**Comment by mfleisch** [comment]
`formula_identifications_Adducts` It should include multiple adducts for the same precursor formula instead of only one hit.  But was a bug that is fixed in 5.6.4

A few notes on that topic: 

* Different adducts of the same precursor formula will have the same `SiriusScore` and are therefore indistinguishable on formula id level, but they differ when it comes to structure id. 
* The different adducts for one precursor formula are only created when running fingerprint prediction.
* when identifying solely the molecular formula all the candidate listed in `formula_identifications_Adducts` are equally good. so you should look at all of them. usually it's just one but for some features there might be a "hand full".
* If you perform structure db search you can take into account which formula  candidate has the best matching structure hit. which is what is stored in `compound_identifications.tsv`  and `compound_identifications_adducts.tsv`
