### ISSUE TITLE
Empty .csv file while trying to use the FBMN export

### ISSUE THREAD

**Issue by Socamibravo** [boecker-lab/sirius#139]
Hi!
I have already computed all compounds (with masses <850Da) and was trying to export to GNPS so I can then use for my FBMN. I tried ticking and unticking the different options to see if it work, but in all cases, I only get correctly the .mgf file. The .csv file only contains the headers, no features inside. What i did was created a folder inside the Sirius option and then inside one file ending with the corresponding extensions. I attach the file I got as .CSV. 
If you know how to fix this, please let me know :) 
I´m using version 5.8.1. 
Btw, thank you for all the work you do! This version works quite faster :)
[Siriusoutput_c18cs_Round8_FractionE_filtered.csv](https://github.com/boecker-lab/sirius/files/13253296/Siriusoutput_c18cs_Round8_FractionE_filtered.csv)

**Comment by mfleisch** [comment]
Hey,
what is your initial input data format? Export of the quant table from SIRIUS does only work if you use mzml/mzxml as input because otherwise the quantitative information is not available anymore.

If you use an preprocessed format as input for SIRIUS (e.g. mgf exported from MZmine) you have to use the FBMN export from MZmine to create an input for FBMN.

If this answers your question please close the issue

Best
Markus

**Comment by Socamibravo** [comment]
Hi mfleisch! 
Thank you very much for your answer! It was very informative. I used a file from MzMine3 (processed, .mgf). 
I wanted to get a .csv file with the canopus predictions in order to connect to the molecular network I have obtained from GNPS (basically scan # and canopus prediction). 
Thank you, 
Sofia
