### ISSUE TITLE
Sirius is not working

### ISSUE THREAD

**Issue by MBJudit** [boecker-lab/sirius#155]
Hello,

I have not been able to use Sirius from yesterday (never had any problem before). 
When I compute an ion, I get the "Formulas", the "Spectra" and the "Trees" information but nothing else. The program continues working but I do not get the structures annotation or Canopus inforamation.
I checked the webservice and all connection services are in green. 

There is this message in the command screen:
"WARNING: Request to Server failed! Try again in 120.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `POOL_CLIENT`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 403 | HTTP-Message:  | HTTP-Request: GET: https://www.csi-fingerid.uni-jena.de/v2.6/api/fingerid/data?predictor=1`"

Can you help, please?
Thanks!
![Captura de ecrã 2024-05-09 145236](https://github.com/boecker-lab/sirius/assets/160124387/258d4c46-0851-48c0-82c1-ef220032d726)

**Comment by marcodaino** [comment]
Same problem for me!!
I have troubles computing my data since yesterday. On May 7th I did some computations (with the same .mgf file) and everything was fine.
Everything with my account ([marco.dainelli@unifi.it](mailto:marco.dainelli@unifi.it)) seems ok. Webservice connection is ok.
I import my data and try to compute one feature, but the process stops at "CSI:FingerID - Fingerprint prediction" whit this message (repeated through time): 

"WARNING: Request to Server failed! Try again in 4.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `POOL_CLIENT`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 403 | HTTP-Message:  | HTTP-Request: GET: [https://www.csi-fingerid.uni-jena.de/v2.6/api/fingerid/data?predictor=1`](https://www.csi-fingerid.uni-jena.de/v2.6/api/fingerid/data?predictor=1)"

**Comment by mfleisch** [comment]
Hey,
unfortunately some piece of the  university infrastructure we rely on is currently not working properly  and it is not within our sphere of influence to fix this issue. Fortunately Bright Giant offered to process the traffic from the academic licenses until this issue is fixed. So you should be able to process your  data again.

**Comment by marcodaino** [comment]
Thank you very much,
I have just tried and it is working.
Have a good day!

**Comment by regarleywater** [comment]
Hello, I am getting this error now (since yesterday). SIRIUS will start computing my job but after a couple minutes it starts to give this error and does not progress. If I restart it, I can move incrementally forward with processing the job, but the file is really big and I cannot do this for the remainder. Below is the code that repeats in the log. Thank you!


Feb 18, 2025 10:28:46 AM de.unijena.bioinf.rest.NetUtils awakeAll
WARNING: Recovered connection successfully and woke up waiting threads.
Feb 18, 2025 10:28:46 AM de.unijena.bioinf.rest.NetUtils awakeAll
WARNING: Recovered connection successfully and woke up waiting threads.
Feb 18, 2025 10:28:46 AM de.unijena.bioinf.rest.NetUtils awakeAll
WARNING: Recovered connection successfully and woke up waiting threads.
Feb 18, 2025 10:28:53 AM de.unijena.bioinf.rest.NetUtils tryAndWait
WARNING: Request to Server failed! Try again in 120.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `JOB_SUBMITTER`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 500 | HTTP-Message: null | HTTP-Request: POST: https://csi.bright-giant.com/v3.0/api/jobs/WEnEThJK9Fn7JjiaJSSDlgGtbJ-eAi_wublrmttnef8qjiCx9bSCN8maHK31AGfS`
Feb 18, 2025 10:28:53 AM de.unijena.bioinf.rest.NetUtils tryAndWait
WARNING: Request to Server failed! Try again in 120.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `JOB_SUBMITTER`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 500 | HTTP-Message: null | HTTP-Request: POST: https://csi.bright-giant.com/v3.0/api/jobs/WEnEThJK9Fn7JjiaJSSDlgGtbJ-eAi_wublrmttnef8qjiCx9bSCN8maHK31AGfS`
Feb 18, 2025 10:28:53 AM de.unijena.bioinf.rest.NetUtils tryAndWait
WARNING: Request to Server failed! Try again in 120.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `JOB_SUBMITTER`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 500 | HTTP-Message: null | HTTP-Request: POST: https://csi.bright-giant.com/v3.0/api/jobs/WEnEThJK9Fn7JjiaJSSDlgGtbJ-eAi_wublrmttnef8qjiCx9bSCN8maHK31AGfS`
