### ISSUE TITLE
re-occuring "not a valid Project Location" error 

### ISSUE THREAD

**Issue by nirshahaf** [boecker-lab/sirius#17]
Hi Sirius team,

Running the latest version from the command line (and as "system" call from within R) on Linux64bit, I keep getting a non indicative error message related to the output directory: "not a valid Project Location". 
By re-iterating with different parameters I conclude that this error message occurs in the following conditions:
* A project file already exists - but the "--recompute" option was not specified
* A project file exists and the "--recompute" option is specified - but not all calculations have completed (i.e. maybe the project file is missing for a recompute and then this error is thrown)
* A project file does not exist and  "--recompute" was specified
* (possibly) also a permission problem - but it's difficult to know because of the non-informative message. 

I did set full permissions at my designated output folder and additionally I noticed the Sirius is independently writing to "/tmp" which is owned by "root" (!) - so I really I do not know what can cause this error. 

Thanks,
Nir

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=he_IL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=he_IL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=he_IL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=he_IL.UTF-8 LC_IDENTIFICATION=C

**Comment by mfleisch** [comment]
Hey Nir,
a valid project location (non compressed) is either an empty directory or a directory that contains a project created by a previous run of SIRIUS. In case you are writing a compressed project file a valid location is either a file that does not yet exist or a file created by a previous run of SIRIUS (`.sirius`).

SIRIUS ties to write to `/tmp` if no output location (`-o`, `--output`) is specified. 

A known problem is that when SIRIUS "fails" because of a wrong command (e.g. non existing parameter) it has already created the output folder, but in a non valid state. The folder is non empty but does also not contain a single compound. In that case you need to delete the folder manually. Could that be the reason for you problem?

This behavior shall be improved in one of the upcoming updates.

In case of an permission problem a "permission denied" error message should be reported in the console.

Best 
Markus

**Comment by nirshahaf** [comment]
Hi Markus,

Thanks for your swift reply! The software behaviour is much clearer now.

I don't want to open another thread - but to briefly ask about the following case:
When evaluating the spectra of chemical standard (CID 23757232) with Sirius + Canopus
I see that the correct chemical formula was identified as second in rank, with a minor score
difference to the incorrect formula at the first rank. Now, from this point the FingerID functions
managed to overcome to ranking mistake and identified the rank#2 structural candidates as
highly better then candidates generated by rank#1- and therefore in the "structure_candidates.tsv"
I got the correct formula for this chemical standard (a stroidal saponin) together with an impressive
identification of a nearly identical structure (different by the location of a hydroxyl group). However,
in the "canopus_summary.tsv" there is just rank#1 with a the wrong chemical class (a monosaccharide).

So, is there an option to set Canopus to annotate all the identified molecular formulas, or - in case of
existing structure annotations - annotate the class corresponding with the best ranking structure?

Have a good week and thanks once more,
Nir.
