### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by bernt-matthias** [boecker-lab/sirius#2]
Running sirius 4.0.1 with parameter `--processors 1` uses more than 100% CPU (according to top).

This is a problem on restrictive HPC systems.

**Comment by mfleisch** [comment]
Hey,
Sorry for the very late response!
The parameter specifies how many threads are available for CPU intense tasks to control the parallelization of the algorithms. Besides that other thread might be occupied for IO or scheduling tasks. Besides that the JVM might also occupy threads e.g. for Garbage Collection. 
However a continuous CPU load of 100% seems not normal. A typical reason for that might be a too small Heap Size. In such cases continuous garbage collecting may result in massive CPU load.

One way to reliably restrict the number of CPU cores of a JVM base software is to use some kind of virtualization (e.g. some container solution).

**Comment by bernt-matthias** [comment]
Is there a good value to set for the Heap Size? I guess this should be `-Xms`, right?

**Comment by mfleisch** [comment]
Hey,
you could either use the environment variable SIRIUS_OPTS or modify the SIRIUS start script.
The parameter to set the max heap size is `-Xmx` (e.g. `-Xmx16G`) 

A good value really depends on the data. But you should not use more than 60% or 70% of the available system memory so that there is some memory left for the ILP solver.
