### ISSUE TITLE
Sirius similarity

### ISSUE THREAD

**Issue by nirshahaf** [boecker-lab/sirius#23]
Hello,

Can you please include a working example and/or a more elaborate documentation of the 'similarity' standalone function?
In particular, are inputs .ms/.mgf spectra files? Is the process similar to comparison of high-resolution fragmentation trees 
(AKA der Hooft/Ric de Vos?)

**Comment by mfleisch** [comment]
Hey,
I added a page to the documentation on this topic.
https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/

Let me know if you miss some information, otherwise the issue can be closed.

**Comment by nirshahaf** [comment]
Hi,

Thanks for adding this info! It surely helps a lot, however:
(i) Would be a good to have the (minimum) build number in brackets next to each tool's description
(ii) A few more specific examples next to each option in the 'similarity' tool would be helpful to technically get some meaningful output run them and to conceptually understand them. So far I could get non-empty results only with the "--cosine" function.

**Comment by mfleisch** [comment]
Hey,
Regarding (i): Sounds like alot of work with not much benefit since there are usually not that many different (working) versions of SIRIUS available due to its dependency on the CSI:FingerID web service.

Regarding (ii): I added a few [examples](https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/#example-1) to the
documentation that hopefully explain how to use the similarity tool.
