### ISSUE TITLE
Exporting results

### ISSUE THREAD

**Issue by ykim7263** [boecker-lab/sirius#36]
Hi all,

Is there any way to export the results including all the results from the batch analysis?
I realized that the "Writing summary" function only contains 1 compound per feature. It would be great if I can extract all the results in a single file?

**Comment by mfleisch** [comment]
Hey,
there is not such file since the number of candidates for a single feature can be very large depending ob the search database and we do not want to store these lists multiple times.

However, when writing summaries, SIRIUS will write a file named `structure_candidates.tsv` for each feature that contains all structure candidates of this feature. So simply concatenating them should do the job I think.

**Comment by yellow-byte** [comment]
How to customize the sorting of summary files, e.g. using CSI:finger's similarity calculation as the primary rule

**Comment by marcus-ludwig** [comment]
If I understand you correctly, you want to sort all compounds individual `structure_candidates.tsv` summary files by the score of the top candidate. 
This is nothing SIRIUS does support or is designed for. SIRIUS provides most information in easy machine-readable files (.tsv, .json). For such specific tasks, you will either have to write your own small script in a language of your choice or you may be able to perform the sorting in Excel after concatenating these summary files.
