### ISSUE TITLE
Data conversion issue: mgf vs. mzML

### ISSUE THREAD

**Issue by stolltho** [boecker-lab/sirius#45]
Hi there.

I have acquired Agilent QTOF LC/MS data (in centroid mode) and converted it w/ msConvert into mgf and mzML.
I have then imported each converted file into Sirius GUI. Depending on the conversion format selected, I get different numbers of imported compounds/MS2. E.g. SIRIUS shows me 1700 MS/MS spectra / compounds for the mgf format, but only 40 for the mzML format. There were definitively more than 40 MS2 spectra acquired.

What could be the reason for this?

Cheers,
Thomas

**Comment by mfleisch** [comment]
Hey Thomas,
This might due to different feature finding algorithms of msConvert and SIRIUS. when using mgf, features are picked by msconvert, when using mzML features are picked by SIRIUS internal feature finding which is focused on features with good MS/MS. 

However,  SIRIUS mzML import was in its early stages back then. So the results might have changed a lot since then.

Since your are using an Agilent instrument you can also export `CEF` format e.g. using masshunter, which is natively supported by SIRIUS.
