### ISSUE TITLE
Implement fragmentation tree method?

### ISSUE THREAD

**Issue by xxing9703** [boecker-lab/sirius#47]
Hi, I'm very interested in implementing the fragmentation tree(FT) method from SIRIUS, ideally a function that takes one molecular formula candidate and MS2 spectra as the input,  and returns a FT along with the score.  Is this available through openAPI? 

Thanks!

Xi

**Comment by marcus-ludwig** [comment]
Hi Xi,

No, currently not. SIRIUS is available as a CLI  (and GUI)  software that reads your data and writes all results into a directory structure with machine-readable files (.json, .tsv). You can specify the molecular formula in the input file (see https://boecker-lab.github.io/docs.sirius.github.io/io/#sirius-ms-format and the downloadable example files for details). Furthermore, you could directly use the library (https://github.com/boecker-lab/sirius-libs).
In the future, we are planning integration with scripting languages that may be based on OpenAPI, but that is currently not available.

If you are planning on wrapping SIRIUS, you may contact us to give us some more information and maybe we can help with some more useful answers.
Also, in such a case, please always highlight the use of SIRIUS and cite the corresponding publication. This is quite important to us. Thanks.

Best,
Marcus

**Comment by xxing9703** [comment]
Hi Marcus,

Thank you very much for the reply. What we really want to try is to incorporate “SIRIUS: fragment tree analysis” in our untargeted analysis -- formula ID, specifically, to add fragment tree scores with some weight in our scorings when evaluating a list of formula candidates for a given m/z peak and its MS2 spectrum.  The formula candidates are neither all possible formulas, nor from a known database matching, but a customized/filtered list dynamically generated in our workflow.   I‘m not sure what is the easiest way for this implementation and hopefully can be fully automated.  Using the library seems ideal, but need some instructions on how to build and use it in a different language (R or Matlab). If running SIRIUS at the back end is required, that’s also fine.  Much appreciated!


Xi

**Comment by mfleisch** [comment]
Hey Xi,
thanks for the details.

You can achieve what you want to do using our internal [.ms file format]( https://boecker-lab.github.io/docs.sirius.github.io/io/#sirius-ms-format) to input your data (including your candidate formulas) and the SIRIUS 4.9.9 command line tool with the following command:

```
sirius -i ./Kaempferol_4_candidates.ms -o ./out-dir sirius 
```

I appended a example input file (`Kaempferol_4_candidates.ms `) which contains the parameter `>CandatiateFormulas` with 4 formula candidates. The above command will compute fragmentation trees only for these 4 candidate formulas.

[Kaempferol_4_candidates.zip](https://github.com/boecker-lab/sirius/files/7523640/Kaempferol_4_candidates.zip)

So you just need to write your data to this format and you are good to go.

The output will be the standard SIRIUS [project-space](https://boecker-lab.github.io/docs.sirius.github.io/io/#sirius-project-space).

On the "compound level" of the output directory you will find the `fomula_candidates.tsv` which contains the TreeScore as well as the IsotopeScore (If MS1 spectrum was available) for each (valid) formula candidate in the input file(s).

Note: 
* One .ms  file can contain data for multiple compounds/features and also multiple MS/MS per compound/feature.
* You can input multiple .ms files at once by e.g. using the parent directory instead of the file.
* The resulting project-space can be also be opened with the SIRIUS GUI, so that the computed fragmentation trees can be reviewed and exported as vector image.
* You need to use at least Version 4.9.9
* Running multiple compounds at once will be more efficiently since you do not have to startup SIRIUS for every computation and it can parallelize more efficiently for larger inputs.

**Comment by xxing9703** [comment]
Thanks very much for updating and providing the detailed notes for usage!  The command line solution works with the attached example ms2 file.  I think I will just need to deal with the I/O for our own data.  will give it a try.  Thanks!

Xi
________________________________

**Comment by mfleisch** [comment]
You are welcome!
