### ISSUE TITLE
CLI slowdowns

### ISSUE THREAD

**Issue by rickhelmus** [boecker-lab/sirius#5]
Hi guys,

First of all congrats on the 4.4 release! Many new features to explore, that's for sure :-)

I am using the CLI version, but noticed two different slowdowns. First of all, it seems execution times ~doubled compared to 4.0.1. Results are different now, so I guess algorithms changed here and there. Still this will affect run times quite a bit with large batch calculations.

Secondly, the CLI tool bundled with GUI package seems to sometimes get stuck for ~1 minute after calculations with a message like `SEVERE10:00:01 - CheckJob (5): Future wait of job was interrupted (Job Canceled)!`. I haven't been able to pin point when this exactly happens. I tried different input data files, command-line option combinations, output folders that were or weren't removed prior to running SIRIUS...

Both situations I noticed on both Windows 10 and Ubuntu Linux. On the latter I made a script to quantify this better:

```bash
#/bin/bash

SIR40=~/Rproj/sirius-linux64-4.0.1/bin/sirius
SIRHL44=~/Rproj/sirius-linux64-headless-4.4.17/bin/sirius
SIR44=~/Rproj/sirius-linux64-4.4.17/bin/sirius

IN=~/Rproj/demo-data/ms/Bicuculline.ms
OUT=~/Rproj/demo-data/sirout

rm -rf $OUT && /usr/bin/time -po sir40.txt $SIR40 -o $OUT $IN
rm -rf $OUT && JAVA_HOME=~/Rproj/zulu11.39.15-ca-jre11.0.7-linux_x64 /usr/bin/time -po sirhl44.txt $SIRHL44 -o $OUT -i $IN formula
rm -rf $OUT && /usr/bin/time -po sir44.txt $SIR44 -o $OUT -i $IN formula

for i in {1..5}
do
    rm -rf $OUT && JAVA_HOME=~/Rproj/zulu11.39.15-ca-jre11.0.7-linux_x64 /usr/bin/time -po sirhl44_$i.txt $SIRHL44 -o $OUT -i $IN formula -p qtof -e CHNOP --ppm-max 5 -c 100
done

for i in {1..5}
do
    rm -rf $OUT && /usr/bin/time -po sir44_$i.txt $SIR44 -o $OUT -i $IN formula -p qtof -e CHNOP --ppm-max 5 -c 100
done
```

The first three tests highlight the first slowdown I described:
```bash
$ cat sir40.txt sirhl44.txt sir44.txt 
real 2.13
user 3.08
sys 0.41
real 4.78
user 7.85
sys 0.60
real 5.15
user 8.09
sys 0.68
```
For the second slowdown I delibaretely added more command-line options, as this seems to increase chances of getting stuck at the end of execution. With the headless version all is fine:
```bash
$ cat sirhl44_*
real 4.63
user 7.49
sys 0.51
real 4.64
user 7.77
sys 0.58
real 4.42
user 7.07
sys 0.60
real 4.80
user 7.71
sys 0.62
real 4.76
user 7.76
sys 0.61
```
For the GUI version not so much:
```bash
rick@rick-VirtualBox:~/Rproj$ cat sir44_*
real 65.71
user 8.88
sys 0.92
real 65.45
user 8.74
sys 0.77
real 65.01
user 8.90
sys 0.86
real 65.36
user 8.58
sys 0.70
real 5.51
user 8.57
sys 0.84
```

As seen from the last run you can see it doesn't always happen. The output below is from when a slowdown happens:

```
May 13, 2020 10:02:07 AM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO  10:02:07 - Sirius Workspace Successfull initialized at: /home/rick/.sirius
INFO  10:02:07 - You run SIRIUS 4.4.17
INFO  10:02:07 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  10:02:07 - Treebuilder priorities are: [CPLEX, GUROBI, GLPK]
INFO  10:02:07 - CPU check done. 2 cores that handle 2 threads were found.
INFO  10:02:07 - Bug reporter initialized.
INFO  10:02:07 - Web API initialized.
INFO  10:02:07 - Application Core started
INFO  10:02:07 - Swing Job MANAGER initialized! 2 : 2
INFO  10:02:08 - CDK InChIGeneratorFactory configured.
INFO  10:02:08 - Running with following arguments: [-o, /home/rick/Rproj/demo-data/sirout, -i, /home/rick/Rproj/demo-data/ms/Bicuculline.ms, formula, -p, qtof, -e, CHNOP, --ppm-max, 5, -c, 100]
WARNING10:02:10 - Could not load CPLEXSolver! Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
WARNING10:02:10 - Could not load GrbSolver! Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  10:02:11 - Workflow has been finished!
INFO  10:02:11 - Executing Postprocessing...
INFO  10:02:11 - Writing summary files...
INFO  10:02:11 - Project-Space summaries successfully written!
INFO  10:02:11 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...
INFO  10:02:11 - Shutting down JobManager
INFO  10:02:11 - Awaiting termination of JobManager
SEVERE10:02:11 - CheckJob (5): Future wait of job was interrupted (Job Canceled)!


Please cite the following publications when using our tool:

Kai Dührkop, Markus Fleischauer, Marcus Ludwig, Alexander A. Aksenov, Alexey V. Melnik, Marvin Meusel, Pieter C. Dorrestein, Juho Rousu, and Sebastian Böcker.
SIRIUS 4: a rapid tool for turning tandem mass spectra into metabolite structure information.
Nat methods, 16, 2019. https://doi.org/10.1038/s41592-019-0344-8

Marcus Ludwig, Louis-Félix Nothias, Kai Dührkop, Irina Koester, Markus Fleischauer, Martin A. Hoffmann, Daniel Petras, Fernando Vargas, Mustafa Morsy, Lihini Aluwihare, Pieter C. Dorrestein, Sebastian Böcker
ZODIAC: database-independent molecular formula annotation using Gibbs sampling reveals unknown small molecules.
bioRxiv, 842740, 2019. https://doi.org/10.1101/842740 (Cite this for ZODIAC)

Kai Dührkop and Sebastian Böcker.
Fragmentation trees reloaded.
J Cheminform, 8:5, 2016. http://dx.doi.org/10.1007/978-3-319-16706-0_10 (Cite this for fragmentation pattern analysis and fragmentation tree computation)

Kai Dührkop, Huibin Shen, Marvin Meusel, Juho Rousu, and Sebastian Böcker.
Searching molecular structure databases with tandem mass spectra using CSI:FingerID.
Proc Natl Acad Sci U S A, 112(41):12580-12585, 2015. http://dx.doi.org/10.1073/pnas.1509788112 (Cite this when using CSI:FingerID)

Sebastian Böcker, Matthias C. Letzel, Zsuzsanna Lipták and Anton Pervukhin.
SIRIUS: decomposing isotope patterns for metabolite identification.
Bioinformatics (2009) 25 (2): 218-224. https://doi.org/10.1093/bioinformatics/btn603 (Cite this for isotope pattern analysis)
```

Please let me know if you need more information.

Thanks,
Rick

**Comment by mfleisch** [comment]
Hey Rick,
thanks for this detailed report.

Regarding the first slowdown: 
In general the algorithms for molecular formula estimation should not have changed dramatically. So this should not be the reason for the runtime increase. Just to be sure, are both versions using the same ILP solver?

In your benchmark, you are starting SIRIUS each time for a single compound. So it is very likely, that you are just measuring the difference in startup time of the different SIRIUS versions, which is slower for SIRIUS 4.4 due to the new Project-Space and the modular sub-tool layout. 

SIRIUS is designed to run large datasets and efficiently parallelizes among different compound, analysis steps and even within the algorithms. So it is generally much more efficient to run many compounds at once than running a separate SIRIUS instance for each compound.

However, we know that this can be annoying in more interactive integrations. We currently started a project to start a local SIRIUS installation as a background service (Rest-Service) that can be queried through a client API which we would like to provide for the scripting languages that are mostly used by the community (e.g. R and Python).
I think that could be a great solution for your use case. Let me know if this is interesting for you.

Regarding the second one:
I have no answer yet. ;-)  We will investigate that, and get back to you.

**Comment by rickhelmus** [comment]
Hi Markus,

Thanks for the quick reply!

The linear solver is kept the same as other solvers are not present on the Linux box.
Do you foresee any way to by-pass the overhead from the new workspace loading? Otherwise 4.0 will remain an option for formula calculation at least.

Background: I'm using SIRIUS as backend for formula/compound annotation in [patRoon](https://github.com/rickhelmus/patRoon). At the moment everything is optimized for single query SIRIUS executions, as this seemed to be a good option for previous versions. I guess in the future I can rewrite it so multiple queries are combined for every SIRIUS call. The REST API sounds interesting, but is probably not exactly the right tool for large batch calculations in this scenario :-)

Thanks again,
Rick

**Comment by mfleisch** [comment]
Hey Rick,
not sure if it is not the right tool for batch calculations. This would competently avoid any startup times of SIRIUS and JVM (except for one initial startup). Further, input data can be passed to SIRIUS in memory instead by writing it to the disc and load it from disc again. I am not talking about a "web service", it is all local. REST is just used to provide an language independent API. Single query executions would not be a problem anymore, because the SIRIUS internal job managing could handle them appropriately.

The main difference from your side would be starting SIRIUS once and sending a rest query instead of executing a command line process. Building the queries is done by the client library, for patRoon you could use the R client I guess? So running SIRIUS tasks would then change to just calling R functions instead of making command line calls.

**Comment by mfleisch** [comment]
I think there is no way to the bypass the project-space because it is the main persistence layer of the CLI. However I will have a short look if we can tune the startup time a bit, but I do not see much potential here.

Nevertheless, starting a JVM and parsing property files for each compound will always be a sub-optimal workflow. 

I think you should either invest in bundle compounds together. With this approach it you should become faster than it was with 4.0.1. Or we can try to get a prototype of the background version ready if your are interested in trying it.
 
Further, SIRIUS development goes in the direction to use more and more dataset wide information for the algorithms (e.g. ZODIAC). So processing data on a per compound basis may hinder you using this features.

Best 
Markus

**Comment by rickhelmus** [comment]
Hi Markus,

Thanks for the extra information! I will definitely try the other approach with calculating multiple formulas on a go. I never realized this was already possible with 4.0 too... will be interesting to compare for sure.

The REST api now also sounds way more interesting! I think I'll start with the bundling approach first, as this will probably require relative few changes in the code.

Thanks again,
Rick

**Comment by mfleisch** [comment]
FYI: here https://github.com/boecker-lab/sirius/issues/11 are some further discussion regarding wrapping SIRIUS in R and the local SIRIUS REST API.
