### ISSUE TITLE
[Feature request] Add option to write all candidates in the summaries

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#50]
Hi again,

Would be nice to have such an option directly for downstream uses of the candidates' list.
I think many people out there have custom bash scripts to cat their own summaries from the folders just because the "default" candidates are too restricted.

Best,

Edit: Having the ability to filter the N top candidates according to a given score, for example, the confidence score, would be even better! 😄

**Comment by mfleisch** [comment]
I had a discussion with @lfnothias on this. Since the information is already available in the compound level summaries we agreed that it might be enough if these files can be written to a location outside of the project-space so that they can be easily processed (without the huge raw results). 

This feature will be available in SIRIUS 5.

Please reopen the issue if this does not tackle the problem.

**Comment by Adafede** [comment]
@mfleisch Thank you very much! 

Do you have an estimate of when it will be (pre-)released?

**Comment by Adafede** [comment]
Looks like I need to subscribe to the web service to get the new features ;P

**Comment by mfleisch** [comment]
Yes an account is needed, but you will not have to descipe when using an email address from your  (academic/non-profit) institution  ;-) Documentation will follow ;-)
