### ISSUE TITLE
Sirius job crashed

### ISSUE THREAD

**Issue by louwenjjr** [boecker-lab/sirius#52]
Hi,

I was running a job with sirius v4.9.3, with around 13,000 non-empty ms/ms spectra from a mgf file with around 200,000 scans. It crashed after some weeks with this error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
# SIGBUS (0x7) at pc=0x00007f4dfaccaea4, pid=6532, tid=6616
#
# JRE version: OpenJDK Runtime Environment Zulu15.32+15-CA (15.0.3+3) (build 15.0.3+3)
# Java VM: OpenJDK 64-Bit Server VM Zulu15.32+15-CA (15.0.3+3, mixed mode, sharing, tiered, g1 gc, linux-amd64)
# Problematic frame:
# V [libjvm.so+0x6e8ea4] G1ParScanThreadState::copy_to_survivor_space(G1HeapRegionAttr, oopDesc*, markWord)+0x2f4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /mnt/scratch/louwe015/NPLinker/crus_canopus/MSV000078836/core.6532)
#
# An error report file with more information is saved as:
# /mnt/scratch/louwe015/NPLinker/crus_canopus/MSV000078836/hs_err_pid6532.log
#
# If you would like to submit a bug report, please visit:
# http://www.azulsystems.com/support/
#
```

The command I ran was:
sirius -i crusemann_full_new/ -o canopus_crusemann_full_new_nomax/ --maxmz 100000 formula structure zodiac canopus

You can find the error raport here:
https://www.bioinformatics.nl/~louwe015/hs_err_pid6532.log

A similar job that I ran without the zodiac step did not crash, so maybe that is causing the issue?

Thanks in advance,
Joris

**Comment by mfleisch** [comment]
Hard to tell what's the problem here, since this is a native library level error from the JDK.
Could it be filesystem related. Probably due to the many files of the large project.

For SIRIUS 5, we updated our project-space (output format) to use much less files. 
We would suggest to check whether this update together with updated new JDK version solves the issue. 

If not, we can dig deeper into this issue.

SIRIUS 5 will be released in a couple of weeks. We will notify here if it is available.

**Comment by louwenjjr** [comment]
Okay sounds good! Thanks for your time.

**Comment by mfleisch** [comment]
Closed due to no further activity. Feel free to reopen if further discussion is needed.
