### ISSUE TITLE
Windows headless CLI seems to ignore JAVA_HOME/PATH

### ISSUE THREAD

**Issue by rickhelmus** [boecker-lab/sirius#6]
Hi guys,

I want to run SIRIUS on AppVeyor (Windows) which has several JDKs/JREs installed by default. The usual way of setting %PATH% and %JAVA_HOME% to the right paths doesn't seem to work with the executable. Interestingly, it does work when executing `java -jar sirius_cli_single_os-4.4.17.jar`. The same occurs on my Windows machine. Is there any other way to override JAVA paths?

Thanks,
Rick

**Comment by mfleisch** [comment]
Hey Rick,
the windows executable only searches the registry for a java install. 
I will see if I can easily add support for the JAVA_HOME environment variable in the `.exe` or I will add a batch script as starter for advanced/custom  configurations. 

Just starting the jar will not work with external ILP solvers because their `jars` will not be in the classpath.

Best 
Markus

**Comment by mfleisch** [comment]
fixed with build 4.4.18
