### ISSUE TITLE
Distributions without JAVA

### ISSUE THREAD

**Issue by bernt-matthias** [boecker-lab/sirius#67]
I was just checking sirius' bioconda recipe and realized that sirius comes with its own openjdk (v15 if I'm not wrong). Wondering if its possible to have a release without java. 

One obvious potential problem seems to be that the latest available jdk in conda-forge seems to be v11.

**Comment by mfleisch** [comment]
Hey Matthias,
you are right it comes with its own JRE (not JDK). There are multiple reasons for that. (Please note the  the JRE (JRE FX) is approx 150MB (200MB) smaller than a full JDK (JDK FX)).

1. The `openjdk` version in conda-forge/bioconda is too old (java-11).
2. SIRIUS relies on JavaFX, which is not included in a standard JDKs and JREs, therefore we are shipping a `zulu-jre-fx` that includes the JavaFX libraries and native libraries. In principle we could easily change our SIRIUS packaging so that it works with a standard `openjdk-15-jdk` (or higher) by adding the JavaFX dependencies to SIRIUS separately.  Nevertheless, SIRIUS will never run with a standard `openjdk-15-jre` though, because it does not contain the native libs (module) needed for JavaFX. 
3. Best practices for Java how java applications should be distributed have started to change since modularization was introduced (approx. since java-9 ??).
The idea behind this concept is that  jdk/jre is split up into separate modules. The jdk-tool `jlink` allows to build custom JREs that contain only the modules really needed by the application application it will be shipped with. The Java application itself (if modularized) will be handled as its own module that has dependencies to JRE modules. This allows to package a java application together with a custom JRE that contains only the modules it really needs. No separate JRE or JDK is needed on the system anymore.

For people where SIRIUS is the only java application int their conda environment a SIRIUS package with bundled custom JRE will be will approx. 150MB - 200MB  smaller than a SIRIUS package without custom JRE that depends on a general purpose JDK. If we might take full advantage of custom build JREs (dropping unused jre modules) in the future this difference might be even larger. 

So I am not sure if depending on a system wide JDK might really be the better solution than shipping a small (custom) JRE with the application. Especial when different Java application depend on different JDK versions. 

FYI:
We are currently discussing the same topic on a conda-forge PR for SIRIUS: https://github.com/conda-forge/staged-recipes/pull/16235
We are trying to move SIRIUS to conda-forge in since quite a while since it also allows to build and distribute windows packages and most of the SIRIUS users are on windows. Unfortunately it has not been approved for merge yet.
This would than replace the bioconda recipe, but since coanda-forge packages are inherited by bioconda this should not really cause problems, or?

**Comment by bernt-matthias** [comment]
Thanks for the detailed explanations. 

Moving to conda-forge should be fine. You might want to ask if anything should be done at bioconda just to avoid that both channels provide updates to SIRIUS.

Btw. I'm currently try to fix the latest bioconda recipe https://github.com/bioconda/bioconda-recipes/pull/34220 .. libz was not found...

**Comment by mfleisch** [comment]
> Btw. I'm currently try to fix the latest bioconda recipe [bioconda/bioconda-recipes#34220](https://github.com/bioconda/bioconda-recipes/pull/34220) .. libz was not found...

Great, thanks for having a look!
