### ISSUE TITLE
CANOPUS prediction based on NPClassifier?

### ISSUE THREAD

**Issue by titodamiani** [boecker-lab/sirius#73]
Hi,
I have a quick question. Are the CANOPUS prediction based on NPClassifier available in a summary `tsv` file (like the `canopus_formula_summary_tsv`?). I cannot find it (I’m using SIRIUS 5.4.1)

Thanks,
Tito

**Comment by kaibioinfo** [comment]
Hi,
not yet, maybe we should add that. You can export them with the new export-prediction subtool, though. It should also work from the GUI. For the CLI the command is

`prediction-export --output npc_summary.csv --npc`

**Comment by mfleisch** [comment]
Hey Tito,
they are available since a few days in the `canopus_formula_summary_tsv`.
Just redownload v5.4.1-SNAPSHOT and it should be there.

Since this is a snapshot version (this means it is rebuild every time we submit a change) the version number is not increased  for every little change. 

Best
Markus
