### ISSUE TITLE
Question: difference between ‘canopus_formula_summary.tsv’ and ‘canopus_compound_summary.tsv’?

### ISSUE THREAD

**Issue by titodamiani** [boecker-lab/sirius#76]
Hi,
I have a quick question. I noticed that the new SIRIUS version now provides two summary files for CANOPUS predictions: `canopus_formula_summary.tsv` and `canopus_compound_summary.tsv`.
Since I found the files to be different (e.g. `canopus_compound_summary.tsv` has more entries), I was wondering what is the difference between them? I could not find it in the online documentation.

Thanks for the help!
Tito

**Comment by mfleisch** [comment]
`canopus_compound_summary.tsv`: Canopus results of the top hits regarding CSI:FingerID structure database score.
`canopus_formula_summary.tsv`: Canopus results of the top hits regarding SIRIUS/ZODIAC Score (No Structure DB Search needed/involved). Since not each formula candidate might have at lease one structure candidate in a structure database, it can happen that there are more results  in  `canopus_formula_summary.tsv` than in the `canopus_compound_summary.tsv` .

**Comment by titodamiani** [comment]
Thanks Markus!!
