### ISSUE TITLE
Spectrum ID and input file names in result files

### ISSUE THREAD

**Issue by JB-MS** [boecker-lab/sirius#9]
Hi,

I would like to make a suggestion for an addition to the result files. I can not find the ID of the input spectra as well as the filename of the input file in the resulting mzTab file or in any other result file, besides these information somewhat hidden in the 'evidence_input_id'. 
I am using .mgf files as input. My problem here is, that all dots and underscores are stripped from the TITLE (e.g. mgf_name.scan_id.scan_id.charge) field in the .mgf file and it is a bit cumbersome to re-extract the required information. Would it be possible to add these information in e.g. the 'SME' part of the file, as these entries point directly to single input spectra?

Cheers,
Johannes

**Comment by mfleisch** [comment]
Hey Johannes, 
we are currently discussing this problem, an we will provide a solution with the next release. 

I will let you know when if the decision made how we do it.

Best
Markus

**Comment by mfleisch** [comment]
Hey Johannes,
* With 4.5.0  we strip the name less aggressive so that only  the following not file path save characters are stripped.
```
:/?#\[]@!$&'( )*+,;=<>%{}|\^"` 
```
* We also fixed a bug that replaced characters with URL syntax (`%` in the names).

With that you should be able to retrieve the information of the input from the file names. 

* The mztab-m has not been updated yet but will be in the future when we are adding quantification information from the lcms alignment.
