### ISSUE TITLE
SIRIUS 5.6.3 Structure Names

### ISSUE THREAD

**Issue by dawa90** [boecker-lab/sirius#99]
Dear SIRIUS Team,

I have recently started using SIRIUS for annotation and noticed, that database hits under the "Structures" tabs often feature rather uncommon names. For example, Tryptophan is annotated as "Pacitron" and Cocaine as "Blizzard".
I was wondering if you could explain how SIRIUS decides which name to display for a given substance and if it is possible to influence this in some way?

**Comment by kaibioinfo** [comment]
Hi,
we used the synonyms list from PubChem and searched automatically for the most simple name (short, consists of few digits and special characters and so on). Turns out this favours uncommon names (Markus called it "street names ;)). When we update our PubChem Database next time we will try to use the name suggested by PubChem itself.
